services:
  evolution_api:
    image: atendai/evolution-api:v2.1.1 # Versi√≥n estable probada
    container_name: evolution_api
    restart: always
    environment:
      - SERVER_URL=https://api.cristianteran.xyz
      - AUTHENTICATION_API_KEY=snk_near_621621#?monday
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_TYPE=postgres
      - DATABASE_CONNECTION_URI=postgresql://cristian_admin:halote621@postgres_db:5432/evolution_db?sslmode=disable
      - DATABASE_SAVE_DATA_INSTANCE=true
    networks:
      - n8n-stack_default

networks:
  n8n-stack_default:
    external: true
