services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: cristian_admin
      POSTGRES_PASSWORD: halote621
      POSTGRES_DB: evolution_db
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    networks:
      - n8n-stack_default

  evolution_api:
    image: atendai/evolution-api:latest
    container_name: evolution_api
    restart: always
    depends_on:
      - postgres_db
    environment:
      - SERVER_URL=https://api.cristianteran.xyz
      - AUTHENTICATION_API_KEY=snk_near_621621#?monday
      # Configuraci√≥n de Base de Datos
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=postgresql://cristian_admin:halote621@postgres_db:5432/evolution_db?sslmode=disable
      - DATABASE_SAVE_DATA_INSTANCE=true
    networks:
      - n8n-stack_default

networks:
  n8n-stack_default:
    external: true
